export const VOCATIONS_ICONS = {
  'http://forums.xenobot.net/images/icons/icon4.png': 'None',
  'http://i.imgur.com/qAXsL2J.png': 'Druid',
  'http://i.imgur.com/rYWmtmw.png': 'Paladin',
  'http://i.imgur.com/jMWSztQ.png': 'Sorcerer',
  'http://i.imgur.com/sKqEwqU.png': 'Knight',
};

export const TIBIA_RL_WORLDS = [
  'Amera',
  'Antica',
  'Astera',
  'Aurera',
  'Aurora',
  'Bellona',
  'Belobra',
  'Beneva',
  'Calmera',
  'Calva',
  'Calvera',
  'Candia',
  'Celesta',
  'Chrona',
  'Danera',
  'Dolera',
  'Duna',
  'Efidia',
  'Eldera',
  'Ferobra',
  'Fidera',
  'Fortera',
  'Garnera',
  'Guardia',
  'Harmonia',
  'Helera',
  'Honbra',
  'Honera',
  'Hydera',
  'Inferna',
  'Iona',
  'Irmada',
  'Julera',
  'Justera',
  'Kenora',
  'Kronera',
  'Laudera',
  'Luminera',
  'Macabra',
  'Magera',
  'Menera',
  'Morta',
  'Mortera',
  'Neptera',
  'Nerana',
  'Nika',
  'Noctera',
  'Olympa',
  'Osera',
  'Pacera',
  'Premia',
  'Pythera',
  'Quilia',
  'Refugia',
  'Relembra',
  'Rowana',
  'Secura',
  'Serdebra',
  'Shivera',
  'Silvera',
  'Solera',
  'Tavara',
  'Tera',
  'Thera',
  'Umera',
  'Unitera',
  'Veludera',
  'Verlana',
  'Vita',
  'Xantera',
  'Xylana',
  'Yanara',
  'Zanera',
  'Zeluna',
];

export const MEDIVIA_WORLDS = [
  'Legacy',
  'Spectrum',
  'Pendulum',
  'Destiny',
];

export const WORLDS_BY_SERVER = {
  tibiaRL: TIBIA_RL_WORLDS,
  medivia: MEDIVIA_WORLDS,
};

export const SERVERS = ['tibiaRL', 'medivia'];
