export const FEATURES = [{
  id: 1,
  to: '/dashboard/bot/list/',
  name: 'Lists',
  image: '/images/features/lists.png',
  available: true,
  description: 'Create Bot lists that are created as channels',
}, {
  id: 2,
  to: '/dashboard/bot/poke/',
  name: 'Poke',
  image: '/images/features/poke.png',
  available: true,
  description: 'Send poke to everyone on your TS',
}, {
  id: 3,
  to: '/dashboard/bot/kick/',
  name: 'Kick & Mass Kick',
  image: '/images/features/kick.png',
  available: true,
  description: 'Kick selected players or all from TS',
}, {
  id: 4,
  to: '/dashboard/bot/drag/',
  name: 'Mass Drag',
  image: '/images/features/mass-drag.png',
  available: true,
  description: 'Dragg all clients to the server',
}, {
  id: 5,
  to: '/dashboard/bot/scanner/',
  name: 'Scann Character',
  image: '/images/features/scanner.jpg',
  available: false,
  description: 'Analize Hidden character',
}, {
  id: 6,
  to: '/dashboard/bot/statics/',
  name: 'War Statics',
  image: '/images/features/war.jpg',
  available: false,
  description: 'Checkout information, like who die most, how frag more, whos winning',
}];
